sh_test(
    name = "arithmetic_test",
    size = "small",
    srcs = ["run_simpl_tests"],
    data = [
        "//simpl:simpl",
        "simpl_progs/arithmetic.simpl",
    ]
)

sh_test(
    name = "printing_test",
    size = "small",
    srcs = ["run_simpl_tests"],
    data = [
        "//simpl:simpl",
        "simpl_progs/printing.simpl",
    ]
)
