name: lint
run-name: ${{ github.actor }} is running linters.
on: [push]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install git+https://github.com/cpplint/cpplint.git
      - run: ./scripts/lint
