name: lint
run-name: ${{ github.actor }} is running linters.
on: [push]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install cpplint==2.0.0
      - run: ./scripts/lint
