name: tests
run-name: ${{ github.actor }} is running all tests.
on: [push]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -y clang expect
        shell: bash
      - run: bazel coverage -c fastbuild --combined_report=lcov //...
        shell: bash
        env:
          CC: clang
          CXX: clang++
      - uses: codecov/codecov-action@v3
        with:
          files: ./bazel-out/_coverage/_coverage_report.dat
