name: tests
run-name: ${{ github.actor }} is running all tests.
on: [push]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y expect
      - run: bazel coverage -c fastbuild --combined_report=lcov //...
      - uses: codecov/codecov-action@v3
        with:
          files: ./bazel-out/_coverage/_coverage_report.dat
